apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "MakeDoc-Examples"
  description: "MakeDoc for TIBCO examples and tips how to generate a documentation and how to use it"
  annotations:
    github.com/project-slug: BehaimITS/MakeDoc-container
    backstage.io/techdocs-ref: dir:./
  links:
    - title: Behaim ITS
      url: https://www.behaimits.com/
      icon: home
spec:
  type: integration
  lifecycle: production
  owner: "group:default/tibco-templates"
  providesApis: ['makedoc-examples-api']
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: makedoc-examples-location
spec:
  targets:
    - ./catalog-api.yaml
