<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
	<html xmlns="http://www.w3.org/1999/xhtml" lang="en-us" xml:lang="en-us">
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <style>
	table thead tr, table thead tr th{	
    background-color: rgb(190, 230, 230);
  }
	body
	{ 
    font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; 
    font-size: 90%; 
    margin: 0px;	
    padding: 0px 0px 0px 0px;
  }
	#exist{
	  width: 1000px;
	  border: rgb(0, 65, 125) 2px solid;
    background-color: rgb(240, 230, 140);
  }
  .header{  
    margin: 0px;
	padding: 0px;
	font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
	font-size: small;
	width: 100%;
	height: 110px;
	background-color: white;
	background-image: url("images/header-row-background-image.png");
	background-repeat: repeat-x;
	}
	.content{  
    margin-left: 10px;
    }
  div#logoBox
  {
  float: left;
  width: 310px;
  height: 110px;
  background-color: transparent;
  }

  div#logoBox img
  {
	height: 80px;
	margin-left: 20px;
	margin-top: 12px;
	padding: 0px;
  }

  div#projectInfoBox
  {
  float: left;
	height: 110px;
	margin-top: 15px;
	margin-left: 5px;
	color: #808080;
  }

  div#projectInfoBox div#projectName
  {
	height: 47px;
	overflow: hidden;
	margin-bottom: 3px;
	font-size: large;
	font-weight: bold;
	color: black;
  }

  div#projectInfoBox p
  {
	 margin: 0px;
   margin-top: 2px;
	 padding: 0px;
  }
  div#title
  {
    margin: 0px;
	  padding: 0px;
	  width: 100%;
	  height: 40px;
	  line-height: 40px;
	  font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
	  font-size: 18px;
	  font-weight: bold;
	  color: white;
	  background-image: url("images/title-background-image.png");
	  background-repeat: repeat-x;
	}
	div#page
  {
    width: 100%;
	 border-left: rgb(0, 65, 125) 1px solid;
    background-image: url("images/small-makedoc-logos-pageTitle.png");
	 background-repeat: no-repeat;
	 background-position: 80% 1px;
  }
  </style>
	<link href="images/favicon.ico" type="image/x-icon" rel="shortcut icon"/>
	<title>Summary of documentation generated by MakeDoc for TIBCO</title>
	<script type="text/javascript">
	function last(){
	<#if script!="No snapshots">
    if (window.location.search.substr(1) == "last")window.location.href="${script}";
    var pole = window.location.search.substr(1).split("&");
    for(i = 0; i < pole.length; i++)
    {
	       if(pole[i].split("=")[0]=="go") window.location.href="${script}?"+pole[i];
    }
  }
  <#else>
    if (window.location.search.substr(1) == "last")window.location.href="index.html";
    var pole = window.location.search.substr(1).split("&");
    for(i = 0; i < pole.length; i++)
    {
          if (window.location.search.substr(1) == "go")window.location.href="index.html";    
    }
  }
  </#if>
  </script>
	</head>
	<body onload="last()">
	<div class="header">
  <div id="logoBox"><img src="images/logoCustomer.png" alt="Customer's logo"></img></div>
      <div id="projectInfoBox">
         <div id="projectName">MakeDoc Repository - ${solution}</div>
         <p>${date}&nbsp; - &nbsp;PIKE</p>
         <p>MakeDoc for TIBCO made by PIKE ELECTRONIC. All Rights Reserved.</p>
  </div>
  </div>
  <div id="title">
  <img src="images/small-makedoc-logos-pageTitle.png"></img>
  </div>
  <div class="content">
  <#if snapshots?is_sequence>
	<h2>Snapshots</h2>
  <table cellspacing="0" cellpadding="4" frame="border" border="1" rules="all">
	<thead align="left">
    <tr>
      <th class="cellrowborder" valign="top">Date</th><th class="cellrowborder" valign="top">Comment</th><th class="cellrowborder" valign="top">Day of the week</th><th class="cellrowborder" valign="top">Last Modification of sources</th><th class="cellrowborder" valign="top">Generated Output</th>
   <#list statHeader as s>
   <th class="cellrowborder" valign="top">Statistics ${s}</th>
   </#list>
	  </tr>
  </thead>
  <tbody>
  <#list snapshots as x>
   <tr>
   <td>${x.date}</td>
   <td>${x.comment}</td>
   <td>${x.weekDay}</td>
   <td>${x.lastModifiedTime}</td>
   <td>
   <#if x.PDF != ""> 
   <#if (x.QA != "")||(x.HTML != "")||(x.DOCX != "")||(x.CHM != "")><a href="${x.PDF}">PDF</a>, 
   <#else>
   <a href="${x.PDF}">PDF</a>
   </#if>
   </#if> 
     
   <#if x.CHM != "">
   <#if (x.QA != "")||(x.HTML != "")||(x.DOCX != "")><a href="${x.CHM}">CHM</a>, 
   <#else>
   <a href="${x.CHM}">CHM</a>
   </#if>
   </#if> 
    
   <#if x.DOCX != "">
   <#if (x.QA != "")||(x.HTML != "")><a href="${x.DOCX}">DOCX</a>, 
   <#else>
   <a href="${x.DOCX}">DOCX</a>
   </#if>
   </#if> 
    
   <#if x.HTML != "">  
   <#if (x.QA != "")><a href="${x.HTML}">HTML</a>, 
   <#else>
   <a href="${x.HTML}">HTML</a>
   </#if>
   </#if>
 
   <#if x.QA != "">
   <a href="${x.QA}?go=qa/qa.html">QA</a>
   </#if>    
   </td>   
   <#if x.analyseStatistics?has_content>
   <#list x.analyseStatistics as stat>  
   <td>
   ${x.statistics}
   <#if stat?has_content>
   ${stat} 
   </td>
   </#if>
   </#list>
   <#else>
   <#list statHeader as s>
   <td> ${x.statistics} </td>
   </#list>
   </#if>
   </tr>
  </#list>  
  </tbody>
  </table>
  <#else>
  <h3>Documentation Portal does not contain any valid snapshot.</h3>
  <p>Repository path: ${snapshots}</p>
  </#if>
  <#if analyse?is_sequence>
  <h2>Analysis</h2>
  <table cellspacing="0" cellpadding="4" frame="border" border="1" rules="all">
	<thead align="left">
    <tr>
      <th class="cellrowborder" valign="top">Date</th><th class="cellrowborder" valign="top">Comment</th><th class="cellrowborder" valign="top">Day of the week</th><th class="cellrowborder" valign="top">Generated Output</th><th class="cellrowborder" valign="top">Old Snapshot</th><th class="cellrowborder" valign="top">New snapshot</th>
	  </tr>
  </thead>
  <tbody> 
  <#list analyse as y>
   <tr>
   <td>${y.date}</td>
   <td>${y.comment}</td>
   <td>${y.weekDay}</td>
   <td>
   <#if y.PDF != ""> 
   <#if (y.QA != "")||(y.HTML != "")||(y.DOCX != "")||(y.CHM != "")><a href="${y.PDF}">PDF</a>, 
   <#else>
   <a href="${y.PDF}">PDF</a>
   </#if>
   </#if> 
     
   <#if y.CHM != "">
   <#if (y.QA != "")||(y.HTML != "")||(y.DOCX != "")><a href="${y.CHM}">CHM</a>, 
   <#else>
   <a href="${y.CHM}">CHM</a>
   </#if>
   </#if> 
    
   <#if y.DOCX != "">
   <#if (y.QA != "")||(y.HTML != "")><a href="${y.DOCX}">DOCX</a>, 
   <#else>
   <a href="${y.DOCX}">DOCX</a>
   </#if>
   </#if> 
    
   <#if y.HTML != "">  
   <#if (y.QA != "")><a href="${y.HTML}">HTML</a>, 
   <#else>
   <a href="${y.HTML}">HTML</a>
   </#if>
   </#if>
   
   <#if y.QA != "">
   <a href="${y.QA}?go=qa/qa.html">QA</a>
   </#if> 
   </td>
   <td>${y.oldSnapshot}</td>
   <td>${y.newSnapshot}</td>
   </tr>
  </#list>  
  </tbody>
  </table>
  </#if>
  <#if quality?is_sequence>
  <h2>Quality Assurance reports</h2>
  <table cellspacing="0" cellpadding="4" frame="border" border="1" rules="all">
	<thead align="left">
    <tr>
      <th class="cellrowborder" valign="top">Date</th><th class="cellrowborder" valign="top">Comment</th><th class="cellrowborder" valign="top">Day of the week</th><th class="cellrowborder" valign="top">Generated Output</th>
	  </tr>
  </thead>
  <tbody>
  <#list quality as z>
   <tr>
   <td>${z.date}</td>
   <td>${z.comment}</td>
   <td>${z.weekDay}</td>
   <td>
   <#if z.PDF != ""> 
   <#if (z.QA != "")||(z.HTML != "")||(z.DOCX != "")||(z.CHM != "")><a href="${z.PDF}">PDF</a>, 
   <#else>
   <a href="${z.PDF}">PDF</a>
   </#if>
   </#if> 
     
   <#if z.CHM != "">
   <#if (z.QA != "")||(z.HTML != "")||(z.DOCX != "")><a href="${z.CHM}">CHM</a>, 
   <#else>
   <a href="${z.CHM}">CHM</a>
   </#if>
   </#if> 
    
   <#if z.DOCX != "">
   <#if (z.QA != "")||(z.HTML != "")><a href="${z.DOCX}">DOCX</a>, 
   <#else>
   <a href="${z.DOCX}">DOCX</a>
   </#if>
   </#if> 
    
   <#if z.HTML != "">  
   <#if (z.QA != "")><a href="${z.HTML}">HTML</a>, 
   <#else>
   <a href="${z.HTML}">HTML</a>
   </#if>
   </#if>
   
   <#if z.QA != "">
   <a href="${z.QA}?go=qa/qa.html">QA</a>
   </#if>  
   </td></tr>
  </#list>  
  </tbody>
  </table>
  </#if>
  <br /><br />
  <div id="exist">
  <p>
    <b>Note:</b><br />
    To get latest generated documentation write parametr ?last in browser.<br />
    <b>Example:</b><br />
    C:\MakeDoc\demo\generated\index.html?last
    <br /><br />
    For navigating directly to the project pages is necessary to use parametr ?go with relative path to the project.<br />
    <b>Example:</b><br />
    C:\MakeDoc\demo\generated\index.html?go=project/projects.html
  </p>
  </div>
  </div>
  </body>
	</html>